name: CI pkg-cmd

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'pkg/istorage/**'

jobs:
  call-workflow-ci-pkg:
    uses: ci_reuse_go.yml
    with:
      test_folder: "pkg"
      ignore_copyright: "cmd/voedger/sys.monitor/site.main"
      ignore_bp3: "true"
      short_test: "true"
      go_race: "false"
      ignore_build: "true"
      test_subfolders: "true"
    secrets:
      reporeading_token: ${{ secrets.REPOREADING_TOKEN }}
      codecov_token: ""
      personal_token: ${{ secrets.PERSONAL_TOKEN }}
